I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 52, in script
    init python:
  File "game/options.rpy", line 53, in <module>
    config.channels = config.channels + ["ambience", "heartbeat"]
Exception: config.channels is not a known configuration variable.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 52, in script
    init python:
  File "/Users/joooyeon/Documents/renpy-8.3.7-sdk/renpy/ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/joooyeon/Documents/renpy-8.3.7-sdk/renpy/python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/options.rpy", line 53, in <module>
    config.channels = config.channels + ["ambience", "heartbeat"]
  File "/Users/joooyeon/Documents/renpy-8.3.7-sdk/renpy/defaultstore.py", line 93, in __getattr__
    raise Exception('config.%s is not a known configuration variable.' % (name))
Exception: config.channels is not a known configuration variable.

macOS-13.6.4-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
MysteryGame 1.0
Sun Jun  8 11:05:34 2025
